Us8 upcoming assignments
SER515Team21/VisualProgramming pull request #36
Opened 2019-10-30 19:46 UTC by vcedgar

Finished task 141, made student view generic

2019-10-31 22:13 UTC, majluni requested changes
I think it would be good to have some tests for AssignmentDb

2019-11-02 19:22 UTC, mattfrautnick commented on src/backend/AssignmentDb.js
> +        fs.unlinkSync(programDbPath);
@vcedgar can you look at US10? I just committed how to fix this because as it is now, it does not work.

2019-11-02 19:24 UTC, mattfrautnick submitted a review, later dismissed
Please update the removeAll for AssignmentsDb, as well as, create tests for AssignmentDb.

2019-11-02 20:41 UTC, vcedgar commented
> I think it would be good to have some tests for AssignmentDb

2019-11-02 22:59 UTC, zlmonroe commented
I just added the "load assign from db". To test it and see the assignment load, you can add this JSON to the database (the AssignmentDB created this, but I didn't leave any calls since we would just have to delete them later)

```
{"name":"Assignment 2","description":"This is the second assignment. It is a hard assignment worth only 100,000 point.","course":"SER334","assignment":"{}","dueDate":"10/02/13 10:28 AM","role":"Assignment","_id":"5AfDJFNLnJ2HHCjb"}
{"name":"Assignment 1","description":"This is the first assignment. It is a practice assignment worth only 1 point.","course":"SER334","assignment":"{}","dueDate":"10/01/13 10:30 PM","role":"Assignment","_id":"9BdfaQdab7xtvjax"}
```

2019-11-03 02:21 UTC, majluni requested changes
I'd say just make it update less often. I'm on mobile so I didn't test it but it looks good

2019-11-03 03:50 UTC, majluni approved these changes

2019-11-03 16:37 UTC, merged